name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/DOCKERFILE
          push: true
          tags: pankajmirdha/testing:${{ github.sha }}
      - name: Commit to another repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/mirdha8846/Git-ops.git
          cd Git-ops/k8s
          sed -i "s|image: pankajmirdha/testing:.*|image: pankajmirdha/testing:${{ github.sha }}|" deployment.yaml
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"
          git config --global url."https://x-access-token:${PAT}@github.com/".insteadOf "https://github.com/"
          git add .
          git commit -m "update deployment config image tag to ${{ github.sha }}"
          git push origin main
         
      # - name: Checkout target repository
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ secrets.TARGET_REPO }}
      #     token: ${{ secrets.TARGET_REPO_PAT }}
      #     path: target-repo

      # - name: Update target repo with new image tag and push
      #   run: |
      #     IMAGE="${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}"
      #     echo "image: $IMAGE" > target-repo/DEPLOYED_IMAGE.txt
      #     cd target-repo
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add DEPLOYED_IMAGE.txt
      #     git commit -m "Update deployed image to $IMAGE" || echo "No changes to commit"
      #     git push