name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Test Job - Runs first
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run tests
        working-directory: ./app
        run: npm test
        env:
          NODE_ENV: test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/coverage/

  # Build and Push Job - Runs only after tests pass
  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Wait for test job to complete successfully
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/DOCKERFILE
          push: true
          tags: pankajmirdha/testing:${{ github.sha }}
      - name: Commit to another repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://${{ secrets.PAT }}@github.com/mirdha8846/Git-ops.git
          cd Git-ops/k8s
          sed -i "s|image: pankajmirdha/testing:.*|image: pankajmirdha/testing:${{ github.sha }}|" deployment.yaml
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "update deployment config image tag to ${{ github.sha }}"
          git push

  # Notification Job - Runs after everything completes
  notify:
    runs-on: ubuntu-latest
    needs: [test, build-and-push]
    if: always()
    steps:
      - name: Check workflow status
        run: |
          if [ "${{ needs.test.result }}" == "success" ] && [ "${{ needs.build-and-push.result }}" == "success" ]; then
            echo "✅ All jobs completed successfully!"
          else
            echo "❌ Some jobs failed!"
            exit 1
          fi
